// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';


function initialState() {
  return /* record */[
          /* counter */0,
          /* notACounter */""
        ];
}

exports.initialState = initialState;
/* No side effect */
