// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function initialState(param) {
  return /* record */[
          /* counter */0,
          /* notACounter */""
        ];
}

exports.initialState = initialState;
/* No side effect */
