// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function reducer(state, action) {
  if (action) {
    return state - 1 | 0;
  } else {
    return state + 1 | 0;
  }
}

exports.reducer = reducer;
/* No side effect */
