// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var NumberReducer$ReasonreactReductiveBoilerplate = require("./NumberReducer.bs.js");
var StringReducer$ReasonreactReductiveBoilerplate = require("./StringReducer.bs.js");

function reducer(state, action) {
  if (action.tag) {
    return /* record */[
            /* counter */state[/* counter */0],
            /* notACounter */StringReducer$ReasonreactReductiveBoilerplate.reducer(state[/* notACounter */1], action[0])
          ];
  } else {
    return /* record */[
            /* counter */NumberReducer$ReasonreactReductiveBoilerplate.reducer(state[/* counter */0], action[0]),
            /* notACounter */state[/* notACounter */1]
          ];
  }
}

exports.reducer = reducer;
/* No side effect */
